const request = async params => {
  const response = await fetch(process.env.NEXT_PUBLIC_VALIDATOR_API_URL, { method: 'POST', body: JSON.stringify(params) }).catch(error => { return null })
  return response && await response.json()
}

export const rpc = async params => await request({ method: 'rpc', ...params })
export const getRPCStatus = async params => await request({ method: 'rpc', path: '/status' })
export const lcd = async params => await request({ method: 'rpc', ...params })
export const getBlock = async height => await request({ method: 'lcd', path: `/cosmos/base/tendermint/v1beta1/blocks/${height}` })
export const getValidatorSets = async (height = 'latest') => await request({ method: 'lcd', path: `/validatorsets/${height}` })
export const getTransaction = async txhash => await request({ method: 'lcd', path: `/cosmos/tx/v1beta1/txs/${txhash}` })
export const searchBlocks = async params => await request({ ...params, method: 'searchBlocks' })
export const searchTransactions = async params => await request({ ...params, method: 'searchTransactions' })
export const getTransactions = async params => await request({ ...params, method: 'getTransactions' })
export const getValidators = async params => await request({ ...params, method: 'getValidators' })
export const getValidatorsVotes = async params => await request({ ...params, method: 'getValidatorsVotes' })
export const searchUptimes = async params => await request({ ...params, method: 'searchUptimes' })
export const searchProposedBlocks = async params => await request({ ...params, method: 'searchProposedBlocks' })
export const searchHeartbeats = async params => await request({ ...params, method: 'searchHeartbeats' })
export const searchPolls = async params => await request({ ...params, method: 'searchPolls' })
export const getChainMaintainers = async params => await request({ ...params, method: 'getChainMaintainers' })
export const getValidatorDelegations = async params => await request({ ...params, method: 'getValidatorDelegations' })
